/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexOldRouteImport } from './routes/index-old'
import { Route as IndexRouteImport } from './routes/index'

const IndexOldRoute = IndexOldRouteImport.update({
  id: '/index-old',
  path: '/index-old',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/index-old': typeof IndexOldRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/index-old': typeof IndexOldRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/index-old': typeof IndexOldRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/index-old'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/index-old'
  id: '__root__' | '/' | '/index-old'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IndexOldRoute: typeof IndexOldRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/index-old': {
      id: '/index-old'
      path: '/index-old'
      fullPath: '/index-old'
      preLoaderRoute: typeof IndexOldRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IndexOldRoute: IndexOldRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
